# Generated by Django 4.2.8 on 2023-12-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('productname', models.CharField(max_length=50)),
                ('productdescription', models.TextField()),
                ('productprice', models.IntegerField()),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('productimg', models.ImageField(upload_to='pics')),
                ('address', models.TextField()),
            ],
        ),
    ]
